In [1]:
import pandas as pd

In [2]:
d=pd.read_csv(r"C:\Users\sivas\Downloads\golf_df.csv")
d

,Outlook,Temperature,Humidity,Windy,Play
0,sunny,hot,high,False,no
1,sunny,hot,high,True,no
2,overcast,hot,high,False,yes
3,rainy,mild,high,False,yes
4,rainy,cool,normal,False,yes
5,rainy,cool,normal,True,no
6,overcast,cool,normal,True,yes
7,sunny,mild,high,False,no
8,sunny,cool,normal,False,yes
9,rainy,mild,normal,False,yes


In [3]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Outlook      14 non-null     object
 1   Temperature  14 non-null     object
 2   Humidity     14 non-null     object
 3   Windy        14 non-null     bool  
 4   Play         14 non-null     object
dtypes: bool(1), object(4)
memory usage: 594.0+ bytes


In [5]:
x=d[["Outlook"]]
y=d["Play"]
x

,Outlook
0,sunny
1,sunny
2,overcast
3,rainy
4,rainy
5,rainy
6,overcast
7,sunny
8,sunny
9,rainy


In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
lp=LabelEncoder()
x1=lp.fit_transform(x)
x1=x1.reshape(-1,1)
x1

c:\Users\sivas\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[2],
       [2],
       [0],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1]])

In [8]:
lp=LabelEncoder()
y1=lp.fit_transform(y)
y1=y1.reshape(-1,1)
y1

array([[0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0]])

In [9]:
from sklearn.naive_bayes import CategoricalNB

In [10]:
model=CategoricalNB()
model.fit(x1,y1)

c:\Users\sivas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


CategoricalNB()

In [11]:
model.predict([[0]])

array([1])